ignore:
  - "**/dagger.hilt.*"
  - "**/hilt_aggregated_deps"
  - "**/Hilt_**"
  - "**/*_HiltModules*"
  - "**/*Factory*"
  - "**/*Module*"
  - "**/designsystem/**/*"
  - "**/ui/**/*"
  - "**/di/**/*"
  - "**/*App*"
  - "**/*Provider*"
  - "**/*NavHost*"
  - "**/ComposableSingletons"
  - "**/*Screen.kt"
  - "**/*Fragment.kt"
  - "**/*Activity.kt"
  - "**/BuildConfig"
