name: danger
description: 'Setup ruby and run danger'

runs:
  using: "composite"
  steps:
    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true

    - name: run danger
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash
      run: bundle exec danger

