name: Run Github CodeQL

on:
  pull_request:
  push:
    branches:
      - 'develop'
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - language: java-kotlin
            build-mode: manual

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-java
        if: matrix.language == 'java-kotlin'

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          build-mode: ${{ matrix.build-mode }}

      - name: Build with Gradle
        if: matrix.language == 'java-kotlin'
        run: ./gradlew assembleDebug --no-daemon --stacktrace

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{matrix.language}}"
