name: Run build and unit test

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '!.github/workflows/**'

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build_test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      security-events: write
    strategy:
      matrix:
        include:
          - language: java-kotlin
            build-mode: manual
          - language: ruby
            build-mode: none

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          build-mode: ${{ matrix.build-mode }}

      - name: set up JDK 17
        uses: actions/setup-java@v4.0.0
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}

      - name: Build with Gradle
        run: ./gradlew assembleDebug --no-daemon --stacktrace

      - name: Run test
        run: ./gradlew testDebug --no-daemon --stacktrace

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{matrix.language}}"

  androidTest:
    uses: ./.github/workflows/instrumented_test.yml

  lint:
    uses: ./.github/workflows/lint_check.yml
    permissions:
      security-events: write

  coverage:
    needs: [ build_test, androidTest ]
    uses: ./.github/workflows/coverage.yml

  danger:
    needs: [ build_test, androidTest, coverage ]
    uses: ./.github/workflows/danger.yml
    if: ${{ always() }}
