name: Run build and unit test

on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - '.github/**'

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build_test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      security-events: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java-kotlin
          build-mode: manual

      - name: set up JDK 17
        uses: actions/setup-java@v4.0.0
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}

      - name: Build with Gradle
        run: ./gradlew assembleDebug --no-daemon --stacktrace

      - name: Run test
        if: always()
        run: ./gradlew testDebug --no-daemon --stacktrace

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-reports
          path: ./*/build/reports/tests/*/index.html

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "kotlin"

  androidTest:
    uses: ./.github/workflows/instrumented_test.yml

  lint:
    uses: ./.github/workflows/lint_check.yml

  coverage:
    uses: ./.github/workflows/coverage.yml
    needs: [ build_test, androidTest ]

  danger:
    uses: ./.github/workflows/danger.yml
    needs: [ build_test, androidTest, coverage ]
    if: ${{ always() }}
