name: Create jacoco coverage report

on:
  workflow_call:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: set up JDK 17
        uses: actions/setup-java@v4.0.0
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}

      - name: Run jacoco coverage report
        run: ./gradlew createDebugCombinedCoverageReport --no-daemon --stacktrace
