name: Run detekt and androidLint

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: set up JDK 17
        uses: actions/setup-java@v4.0.0
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Run detekt
        run: ./gradlew detekt --no-daemon

      - name: Run androidLint
        run: ./gradlew lintDebug --no-daemon

      - name: Upload lint reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lint-reports
          path: |
            ./*/build/reports/list-results-*.html
            ./*/build/reports/detekt/detekt.html

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ./*/build/reports/*.sarif
          category: lint
