name: Run detekt and androidLint

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-java

      - name: Run detekt
        run: ./gradlew detekt --no-daemon

      - name: Upload detekt SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ./build/reports/detekt/merge.sarif
          category: detekt

      - name: Run androidLint
        run: ./gradlew lintDebug --no-daemon

      - name: Upload androidLint SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ./app/build/reports/lint-results-debug.sarif
          category: androidLint

      - uses: ./.github/actions/danger
